# Generated by Django 5.2.4 on 2025-07-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("talkie_app", "0002_talkie_user_models_desvcription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="talkie_user_models",
            old_name="desvcription",
            new_name="description",
        ),
    ]
