# Generated by Django 5.2.4 on 2025-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talkie_app", "0003_rename_desvcription_talkie_user_models_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkie_user_models",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
