# Generated by Django 5.2.4 on 2025-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talkie_app", "0004_talkie_user_models_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkie_user_models",
            name="duration",
            field=models.CharField(default="", max_length=50),
        ),
    ]
