# Generated by Django 5.2.4 on 2025-07-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talkie_app", "0005_talkie_user_models_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkie_user_models",
            name="exe_file",
            field=models.FileField(blank=True, null=True, upload_to="executables/"),
        ),
    ]
